Create React App
st-tuduong/FE-React-Duong-Phan-Cam-Tu-ST10062 pull request #1
Opened 2022-06-30 10:30 UTC by st-tuduong

##### References
> Describe what it related
-Implement React Fashion App

2022-06-30 11:26 UTC, st-trangnguyen requested changes
Tú,
Ngoài cái banner, footer, header là layout ra thì những cái product list, shopify nó có liên quan chi đến layout đâu em. em tạo 1 folder tên là `partials` và đưa những thứ ko liên quan đến layout ra ngoài.

Subscriber có phải sẽ dùng đi dùng lại nhiều lần ko mà phải tách ra em?

Những cái như header hay footer đồ thường mình sẽ dùng hết cho tất cả các trang ko chỉ mình home ko, thay vì em đi import từng trang thì em sẽ import ở cái lớn nhất đang bọc cái pages nhé

Em fix những cái này đi rùi review tiếp

2022-06-30 18:07 UTC, st-vantran commented on fashion-app/src/app/shared/components/partials/ProductList.tsx
> +const ProductList = () => {
Này em sử dụng thẳng thằng constant/product ở phần return là sai rồi.
Vì component `ProductList` này em dùng 2 nơi: `for-you` và `product`. Nên có thể 2 section đó sẽ có các data products khác nhau.
Nên do đó em phải truyền thằng constant/product này ở `props` hoặc cách nào đó (nếu em nghĩ ra) để mỗi thằng section sẽ có 1 data khác nhau nhé em.

2022-06-30 18:07 UTC, st-vantran commented on fashion-app/src/app/shared/components/partials/ProductList.tsx
> +          <li className="product-item product-sale col-3 col-sm-6">
Nên tạo 1 component Product ở đây nhé em

2022-06-30 18:07 UTC, st-vantran commented on fashion-app/src/app/shared/components/partials/Shopify.tsx
> +import Icon from "../../../asset/icon";
thằng shared/components/partials này thường để Button, Modal, Input,.... nhé em.
Thằng Shopify dùng riêng cho home nên đưa vào home nhé

2022-06-30 18:07 UTC, st-vantran commented on fashion-app/src/app/shared/components/partials/ProductList.tsx
> +      {products.map(function (product) {
Chuyển arrow function nhé e

2022-06-30 18:15 UTC, st-vantran commented on fashion-app/src/app/shared/components/partials/Collection.tsx
> +          <li className="col-6 col-sm-12">
Như những thằng li này em nên tạo 1 component nhé

2022-06-30 18:15 UTC, st-vantran commented on fashion-app/src/app/pages/home/Home.tsx
> +                  <button className="btn btn-primary col-sm-6">
Thường button sẽ tạo 1 component rồi cho vào `shared/components/partials/ `

2022-07-01 01:06 UTC, st-vantran commented on fashion-app/src/app/shared/partials/button.tsx
> +    <a href="#" className={`btn btn-${type}`}>{text}</a>
Button mà sao render ra thẻ a em?

2022-07-01 01:06 UTC, st-vantran commented on fashion-app/src/app/shared/interfaces/shopify.ts
> +}
New line.

2022-07-01 01:06 UTC, st-vantran commented on fashion-app/src/app/shared/partials/button.tsx
> +import { IButton } from "../interfaces/button";
Folder này nên nằm trong components chớ

2022-07-01 06:58 UTC, st-vantran commented
Continue upgrading the structure of the app in another PR.
I will merge this PR temporarily!

2022-07-01 06:59 UTC, merged