Implement Fashion-App Use Redux
st-tuduong/FE-React-Duong-Phan-Cam-Tu-ST10062 pull request #4
Opened 2022-07-05 10:28 UTC by st-tuduong

## Description
- Implement Fashion-App Use Redux

## Screen UI
![image](https://user-images.githubusercontent.com/106951774/177305332-04f3a281-205a-4c2a-a4b7-a2613d31b030.png)

2022-07-05 15:55 UTC, st-vantran commented on fashion-app/src/app/pages/cart/Cart.tsx
> +  const {carts} = useSelector((state: any) => state.products);
Em xem đặt lại tên nhé, lấy data là carts nhưng đặt tên state là products

2022-07-05 15:55 UTC, st-vantran commented on fashion-app/src/app/pages/home/home.reducers.ts
> +        (item: any) => item.id === action.payload.products.id
Hiện tại em đang truyền lên action cả trường products luôn:
```ts
products: {
id: 1,
name: abc,
}
```
nên truyền thẳng data lên luôn nhé em, bỏ thằng products đi

2022-07-05 15:55 UTC, st-vantran commented on fashion-app/src/app/pages/home/home.reducers.ts
> +        return {
Vậy trường hợp này không lưu local hả em?

2022-07-05 15:55 UTC, st-vantran commented on fashion-app/src/app/pages/home/partials/ProductItem.tsx
> +const ProductItem = ({ products }: IProductItemProps) => {
product item mà sao truyền `products` số nhiều nhỉ, `product` số ít mới đúng chớ em

2022-07-05 15:55 UTC, st-vantran commented on fashion-app/src/app/store/app.actions.ts
> +export default store;
add new line

2022-07-06 02:24 UTC, st-trangnguyen requested changes

2022-07-06 02:24 UTC, st-trangnguyen commented on fashion-app/src/app/pages/cart/Cart.tsx
> +          <SectionCart carts={carts}/>
Rank A: Dùng redux rùi mà còn truyền data xuống bằng props là sao Tú? Hôm qua chị chưa giải thích tại sao chúng ta dùng redux à????

2022-07-06 02:28 UTC, st-trangnguyen requested changes

2022-07-06 02:28 UTC, st-trangnguyen commented on fashion-app/src/app/pages/cart/cart.reducers.ts
> +  carts: getData('cart', []),
Rank B: Tạo sao lại có `s` nhỉ, trang ni có nhiều giỏ hàng à? đặt tên biến cũng phải đúng ngữ cảnh nghen

2022-07-06 08:10 UTC, st-vantran commented on fashion-app/src/app/pages/home/Home.tsx
> +        products={data}
products lưu store rồi thì vào thằng thằng Productlist lấy ra thôi em

2022-07-06 08:10 UTC, st-vantran commented on fashion-app/src/app/pages/cart/cart.reducers.ts
> +        storeData('cart', newCart);
Em tìm cách check khi cart thay đổi thì set Local nhé. Để 1 nơi duy nhất thôi thay vì set từng lần thay đổi như thế này

2022-07-06 10:13 UTC, st-trangnguyen commented on fashion-app/src/app/pages/cart/partials/CartItem.tsx
> +const CartItem = ({ cart }: ICartItemProps) => {
Rank B: Mấy cái tên của prop này cũng vậy, đặt lại cho đúng hết

2022-07-06 10:15 UTC, st-trangnguyen commented on fashion-app/src/app/pages/cart/partials/SectionCart.tsx
> +        <CartList cart={cart} />
Rank A: đây là comment cuối cùng về việc sử dụng redux rồi mà vẫn truyền state xún như prop nha Tú. cuối cùng em đã thực sự hiểu tại sao cần dùng redux chưa vậy

<img width="818" alt="image" src="https://user-images.githubusercontent.com/63229420/177528062-ccb683fb-7c86-4d70-b9f2-125231aa954b.png">

2022-07-06 10:17 UTC, st-trangnguyen commented on fashion-app/src/app/pages/home/Home.tsx
> +import campaigns from '../../shared/constant/campaign';
Rank B: Mấy cái này em đưa vào trong kia component của nó luôn đi, ko cần import ở đây rồi đưa data xún = props. data của component vào thì define ở component đó, ko cần phải define ở cha rồi truyền xún = props.
trừ khi đó là data của thằng cha, và thằng con cần dùng.

2022-07-06 10:20 UTC, st-trangnguyen commented on fashion-app/src/app/pages/home/home.reducers.ts
> +  error: "",
Rank C: dùng cái dấu chi đây ri?

2022-07-06 10:24 UTC, st-trangnguyen commented on fashion-app/src/app/pages/home/partials/ProductList.tsx
> +      {products.map((products: IProduct) => {
Rank B: khi map 1 mảng thì mình sẽ lấy đc từng item, mà thêm `s` làm chi Tú? rồi truyền vô product item là dùng số nhiều, em ko thấy lấn cấn khi đặt tên à

2022-07-07 04:44 UTC, st-vantran approved these changes

2022-07-07 04:44 UTC, st-vantran commented on fashion-app/src/app/pages/Page.tsx
> +export default Page;
add new line

2022-07-07 06:39 UTC, st-trangnguyen commented on fashion-app/src/app/pages/home/Home.tsx
> +    dispatch<any>(getPosts());
get Posts ???? là sao nhỉ

2022-07-07 06:40 UTC, st-trangnguyen approved these changes
Cần đầu tư thêm chất xám vào cách đặt tên biến nha bé

2022-07-07 06:40 UTC, merged