Implement Fashion App Use Redux Saga
st-tuduong/FE-React-Duong-Phan-Cam-Tu-ST10062 pull request #6
Opened 2022-07-07 08:00 UTC by st-tuduong

## Description 
- Implement Fashion App Use Redux Saga

2022-07-07 09:55 UTC, st-trangnguyen requested changes

2022-07-07 09:55 UTC, st-trangnguyen commented on fashion-app/src/app/app.reducers.ts
> +  home: homeReducer,
Rank B: Đặt tên mấy cái reducer này khó hiểu quá bé, có thể đặt là productReducer, categoryReducer

Sau này em đi đâu dùng cũng được, chứ em đặt là home mà đi những trang ko phải là home dùng cũng kì

2022-07-07 09:55 UTC, st-trangnguyen commented on fashion-app/src/app/pages/home/home.middlewares.ts
> +const ENDPOINT = 'https://6088e20da6f4a300174271e7.mockapi.io';
Rank C: em học theo cái ni để tạo const cho những cái này Tú, bây giờ ở home middleware em khai báo sau này những chỗ middleware khác dùng thì như thế nào?

https://github.com/st-trangnguyen/b-react-ts/tree/main/src/config

2022-07-07 09:55 UTC, st-trangnguyen commented on fashion-app/src/app/pages/home/partials/ProductItem.tsx
> +  const getCategoriesItem = categories.find((item: any) => item.id === +product.category)
Rank A: Dùng useEffect là dùng useState đàng hoàng bé.
Dùng useEffect để watch đc lúc nào categories thay đổi, là setState để update UI.

2022-07-08 02:42 UTC, st-vantran approved these changes

2022-07-08 02:42 UTC, st-vantran commented on fashion-app/src/app/pages/home/home.middlewares.ts
> +  console.log(`${environment.apiBaseUrl}/${ENDPOINT.products}`)
Lần sau check xoá hết log trên PR nghen em

2022-07-08 02:42 UTC, st-vantran commented on fashion-app/src/app/pages/home/partials/ProductItem.tsx
> +  const [categoryName, setCategoryName] = useState();
Nên để giá trị mặc định cho thằng state nhé em

2022-07-08 02:46 UTC, merged